version: "3.8"

networks:
  web-server-network:
    name: web-server-network

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    networks:
      - web-server-network
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    networks:
      - web-server-network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mariadb:/var/lib/mysql
